import type { GameEventKind } from '../game/world';

// Every sound the game can make. The audio files are original, generated by
// scripts/make-audio.py (no third-party audio, nothing to attribute).

export type SoundId = GameEventKind | 'tap' | 'gameover' | 'ambient';

export interface SoundConfig {
  /** 0..1, before the master volume. */
  volume: number;
  /** Ignore requests arriving sooner than this after the last play. */
  minGapMs: number;
  /** Simultaneous overlapping instances (round-robin). */
  voices: number;
}

export const SOUND_CONFIG: Record<SoundId, SoundConfig> = {
  fire:        { volume: 0.50, minGapMs: 90,   voices: 3 },
  hit:         { volume: 0.50, minGapMs: 60,   voices: 3 },
  explode:     { volume: 0.90, minGapMs: 80,   voices: 3 },
  explodeBoss: { volume: 1.00, minGapMs: 500,  voices: 1 },
  ram:         { volume: 0.80, minGapMs: 200,  voices: 2 },
  damage:      { volume: 0.80, minGapMs: 120,  voices: 2 },
  boss:        { volume: 0.90, minGapMs: 2000, voices: 1 },
  pickup:      { volume: 0.50, minGapMs: 70,   voices: 3 },
  crate:       { volume: 0.60, minGapMs: 150,  voices: 2 },
  unlock:      { volume: 0.80, minGapMs: 1000, voices: 1 },
  storm:       { volume: 0.70, minGapMs: 3000, voices: 1 },
  dock:        { volume: 0.70, minGapMs: 300,  voices: 1 },
  undock:      { volume: 0.70, minGapMs: 300,  voices: 1 },
  tap:         { volume: 0.50, minGapMs: 40,   voices: 2 },
  gameover:    { volume: 0.80, minGapMs: 1000, voices: 1 },
  ambient:     { volume: 0.25, minGapMs: 0,    voices: 1 },
};

export const ALL_SOUND_IDS = Object.keys(SOUND_CONFIG) as SoundId[];

/** Asset file (without extension) for each sound; keep in sync with make-audio.py. */
export const SOUND_FILES: Record<SoundId, string> = {
  fire: 'fire', hit: 'hit', explode: 'explode', explodeBoss: 'explode_boss', ram: 'ram',
  damage: 'damage', boss: 'boss', pickup: 'pickup', crate: 'crate', unlock: 'unlock',
  storm: 'storm', dock: 'dock', undock: 'undock', tap: 'tap', gameover: 'gameover', ambient: 'ambient',
};
